# Generated by Django 3.1.4 on 2020-12-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='poem',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
